### ISSUE TITLE
Can't join from 1.7

### ISSUE THREAD

**Issue by RedolentHalo** [Xernium/Travertine#1]
![image](https://user-images.githubusercontent.com/86344714/219925764-e0c23bbf-c77a-4329-8989-b0e7da9f280f.png)
hey i am having issues joining from 1.7

**Comment by air-anchor** [comment]
Tell me how to reproduce and I will try to fix.
What server version?
What client version?
Using ViaVersion + ViaRewind?

**Comment by RedolentHalo** [comment]
Server version 1.8.9
1.7
Yes

**Comment by air-anchor** [comment]
Cannot reproduce. Tried just about everything.
Use ViaVersion-dev and normal ViaRewind on server
**will not work if installed on proxy** and that wont be fixed. Is vias fault.
